#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
# shellcheck source=scripts/agent-learning/lib.sh
. "${SCRIPT_DIR}/lib.sh"

usage() {
    cat <<'USAGE'
Usage:
  scripts/agent-learning/propose-skill-update.sh --skill-file PATH --episodes PATH [options]

Options:
  --skill-file PATH  Skill markdown file to update.
  --episodes PATH    Episode JSONL file generated by build-episodes.sh.
  --output PATH      Unified diff output. Defaults to STORE/skill-update.patch.
  --apply            Apply the generated skill update instead of only writing a patch.
  --store-dir PATH   Artifact store directory. Defaults to AGENT_LEARNING_DIR or .agent-learning.
USAGE
}

skill_file=""
episodes_file=""
output_file=""
apply_update=0
option_value=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        --skill-file)
            option_value="${2:-}"
            al_require_option_value "$1" "${option_value}"
            skill_file="${option_value}"
            shift 2
            ;;
        --episodes)
            option_value="${2:-}"
            al_require_option_value "$1" "${option_value}"
            episodes_file="${option_value}"
            shift 2
            ;;
        --output)
            option_value="${2:-}"
            al_require_option_value "$1" "${option_value}"
            output_file="${option_value}"
            shift 2
            ;;
        --apply)
            apply_update=1
            shift
            ;;
        --store-dir)
            option_value="${2:-}"
            al_require_option_value "$1" "${option_value}"
            export AGENT_LEARNING_DIR="${option_value}"
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "Error: unknown option '$1'." >&2
            usage >&2
            exit 2
            ;;
    esac
done

al_require_command jq

if [ -z "${skill_file}" ] || [ -z "${episodes_file}" ]; then
    echo "Error: --skill-file and --episodes are required." >&2
    exit 2
fi

if [ ! -f "${skill_file}" ]; then
    echo "Error: skill file not found: ${skill_file}" >&2
    exit 2
fi

if [ ! -s "${episodes_file}" ]; then
    echo "Error: episode file is empty or missing: ${episodes_file}" >&2
    exit 2
fi

store_dir="$(al_store_dir)"
output_file="${output_file:-${store_dir}/skill-update.patch}"
mkdir -p "$(dirname "${output_file}")"

skill_file_path="$(al_absolute_path "${skill_file}")"
output_file_path="$(al_absolute_path "${output_file}")"
if [ "${skill_file_path}" = "${output_file_path}" ]; then
    echo "Error: --output must not point to --skill-file." >&2
    exit 2
fi

tmp_dir="$(mktemp -d)"
cleanup() {
    rm -rf "${tmp_dir}"
}
trap cleanup EXIT

notes_file="${tmp_dir}/notes.md"
new_skill_file="${tmp_dir}/$(basename "${skill_file}")"

jq -r --arg skill_file "${skill_file}" '
    def normalize_path:
        gsub("^\\./"; "")
        | gsub("/+"; "/")
        | sub("/$"; "");
    def path_matches($left; $right):
        ($left | normalize_path) as $left_path
        | ($right | normalize_path) as $right_path
        | $left_path == $right_path
          or ($left_path | endswith("/" + $right_path))
          or ($right_path | endswith("/" + $left_path));
    select((.skill_ref // "") as $ref | ($ref != "") and path_matches($skill_file; $ref))
    | "- " + (.intervention.type // "learning") + ": " + (.intervention.summary // "capture follow-up")
      + (if ((.good_output // "") | length) > 0 then " Expected behavior: " + ((.good_output // "") | gsub("[\r\n]+"; " ") | .[0:180]) else "" end)
' "${episodes_file}" | awk '!seen[$0]++' >"${notes_file}"

if [ ! -s "${notes_file}" ]; then
    echo "Error: no usable learning notes found in ${episodes_file}." >&2
    exit 1
fi

awk '
    BEGIN { skip = 0 }
    /^## Learning Notes[[:space:]]*$/ { skip = 1; next }
    skip && /^## / { skip = 0 }
    !skip { print }
' "${skill_file}" >"${new_skill_file}"

{
    printf '\n## Learning Notes\n\n'
    cat "${notes_file}"
    printf '\n'
} >>"${new_skill_file}"

if [ "${apply_update}" -eq 1 ]; then
    cp "${new_skill_file}" "${skill_file}"
    echo "Skill updated: ${skill_file}"
    exit 0
fi

diff -u "${skill_file}" "${new_skill_file}" >"${output_file}" || true

if [ ! -s "${output_file}" ]; then
    echo "Error: optimizer produced an empty patch." >&2
    exit 1
fi

echo "Skill update patch written: $(al_relative_path "${output_file}")"
