version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'Kravalg'
    groups:
      all-deps:
        patterns:
          - '*'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/tests/Load'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'Kravalg'
    groups:
      all-deps:
        patterns:
          - '*'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'
