framework:
  cache:
    app: cache.adapter.redis
    default_redis_provider: app.redis_connection

    pools:
      app:
        adapter: cache.adapter.redis
        default_lifetime: 86400
        provider: app.redis_connection

      cache.user:
        adapter: cache.adapter.redis
        default_lifetime: 600
        provider: app.redis_connection
        tags: true
