# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    handle_all_throwables: true
    default_locale: en
    enabled_locales: [en, uk]
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    serializer:
        mapping:
            paths: ['%kernel.project_dir%/config/serialization']

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
