extends:
  - spectral:oas

rules:
  api-info-requires-contact:
    description: The info object must define a contact.
    severity: error
    given: $.info
    then:
      field: contact
      function: truthy

  api-info-requires-license:
    description: The info object must declare a license.
    severity: error
    given: $.info
    then:
      field: license
      function: truthy

  api-info-requires-description:
    description: The info object must include a description.
    severity: error
    given: $.info
    then:
      field: description
      function: truthy

  api-tags-require-description:
    description: Each tag should describe its purpose.
    severity: error
    given: $.tags[*]
    then:
      field: description
      function: truthy

  operation-must-have-summary:
    description: Operations must provide a summary.
    severity: error
    given: $.paths[*][get,put,post,delete,patch,options,head,trace]
    then:
      field: summary
      function: truthy

  operation-must-have-description:
    description: Operations must provide a description.
    severity: error
    given: $.paths[*][get,put,post,delete,patch,options,head,trace]
    then:
      field: description
      function: truthy

  operation-must-have-tags:
    description: Operations must provide tags.
    severity: error
    given: $.paths[*][get,put,post,delete,patch,options,head,trace]
    then:
      field: tags
      function: truthy

  operation-requires-2xx-response:
    description: Operations must define at least one 2xx response.
    severity: error
    given: $.paths[*][get,put,post,delete,patch,options,head,trace]
    then:
      field: responses
      function: schema
      functionOptions:
        schema:
          type: object
          additionalProperties: true
          anyOf:
            - required: [default]
            - required: ['200']
            - required: ['201']
            - required: ['202']
            - required: ['203']
            - required: ['204']
            - required: ['205']
            - required: ['206']
            - required: ['207']
            - required: ['208']
            - required: ['209']
            - required: ['210']
            - required: ['211']
            - required: ['212']
            - required: ['213']
            - required: ['214']
            - required: ['215']
            - required: ['216']
            - required: ['217']
            - required: ['218']
            - required: ['219']
            - required: ['220']
            - required: ['221']
            - required: ['222']
            - required: ['223']
            - required: ['224']
            - required: ['225']
            - required: ['226']
            - required: ['227']
            - required: ['228']
            - required: ['229']
            - required: ['230']
            - required: ['231']
            - required: ['232']
            - required: ['233']
            - required: ['234']
            - required: ['235']
            - required: ['236']
            - required: ['237']
            - required: ['238']
            - required: ['239']
            - required: ['240']
            - required: ['241']
            - required: ['242']
            - required: ['243']
            - required: ['244']
            - required: ['245']
            - required: ['246']
            - required: ['247']
            - required: ['248']
            - required: ['249']
            - required: ['250']
            - required: ['251']
            - required: ['252']
            - required: ['253']
            - required: ['254']
            - required: ['255']
            - required: ['256']
            - required: ['257']
            - required: ['258']
            - required: ['259']
            - required: ['260']
            - required: ['261']
            - required: ['262']
            - required: ['263']
            - required: ['264']
            - required: ['265']
            - required: ['266']
            - required: ['267']
            - required: ['268']
            - required: ['269']
            - required: ['270']
            - required: ['271']
            - required: ['272']
            - required: ['273']
            - required: ['274']
            - required: ['275']
            - required: ['276']
            - required: ['277']
            - required: ['278']
            - required: ['279']
            - required: ['280']
            - required: ['281']
            - required: ['282']
            - required: ['283']
            - required: ['284']
            - required: ['285']
            - required: ['286']
            - required: ['287']
            - required: ['288']
            - required: ['289']
            - required: ['290']
            - required: ['291']
            - required: ['292']
            - required: ['293']
            - required: ['294']
            - required: ['295']
            - required: ['296']
            - required: ['297']
            - required: ['298']
            - required: ['299']

  operation-requires-problem-response:
    description: Operations must define at least one 4xx response.
    severity: error
    given: $.paths[*][get,put,post,delete,patch,options,head,trace]
    then:
      field: responses
      function: schema
      functionOptions:
        schema:
          type: object
          additionalProperties: true
          anyOf:
            - required: [default]
            - required: ['400']
            - required: ['401']
            - required: ['402']
            - required: ['403']
            - required: ['404']
            - required: ['405']
            - required: ['406']
            - required: ['407']
            - required: ['408']
            - required: ['409']
            - required: ['410']
            - required: ['411']
            - required: ['412']
            - required: ['413']
            - required: ['414']
            - required: ['415']
            - required: ['416']
            - required: ['417']
            - required: ['418']
            - required: ['419']
            - required: ['420']
            - required: ['421']
            - required: ['422']
            - required: ['423']
            - required: ['424']
            - required: ['425']
            - required: ['426']
            - required: ['427']
            - required: ['428']
            - required: ['429']
            - required: ['430']
            - required: ['431']
            - required: ['432']
            - required: ['433']
            - required: ['434']
            - required: ['435']
            - required: ['436']
            - required: ['437']
            - required: ['438']
            - required: ['439']
            - required: ['440']
            - required: ['441']
            - required: ['442']
            - required: ['443']
            - required: ['444']
            - required: ['445']
            - required: ['446']
            - required: ['447']
            - required: ['448']
            - required: ['449']
            - required: ['450']
            - required: ['451']
            - required: ['452']
            - required: ['453']
            - required: ['454']
            - required: ['455']
            - required: ['456']
            - required: ['457']
            - required: ['458']
            - required: ['459']
            - required: ['460']
            - required: ['461']
            - required: ['462']
            - required: ['463']
            - required: ['464']
            - required: ['465']
            - required: ['466']
            - required: ['467']
            - required: ['468']
            - required: ['469']
            - required: ['470']
            - required: ['471']
            - required: ['472']
            - required: ['473']
            - required: ['474']
            - required: ['475']
            - required: ['476']
            - required: ['477']
            - required: ['478']
            - required: ['479']
            - required: ['480']
            - required: ['481']
            - required: ['482']
            - required: ['483']
            - required: ['484']
            - required: ['485']
            - required: ['486']
            - required: ['487']
            - required: ['488']
            - required: ['489']
            - required: ['490']
            - required: ['491']
            - required: ['492']
            - required: ['493']
            - required: ['494']
            - required: ['495']
            - required: ['496']
            - required: ['497']
            - required: ['498']
            - required: ['499']

  parameter-description-required:
    description: Parameters must include a description.
    severity: error
    given: $.paths[*][get,put,post,delete,patch,options,head,trace].parameters[*]
    then:
      field: description
      function: truthy

  oas3-unused-component: false
