<?php

declare(strict_types=1);

use NunoMaduro\PhpInsights\Domain\Insights\CyclomaticComplexityIsHigh;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenNormalClasses;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenTraits;
use PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\UselessOverridingMethodSniff;
use PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineLengthSniff;
use PHP_CodeSniffer\Standards\Generic\Sniffs\Formatting\SpaceAfterNotSniff;
use PHP_CodeSniffer\Standards\Generic\Sniffs\Strings\UnnecessaryStringConcatSniff;
use SlevomatCodingStandard\Sniffs\Classes\SuperfluousExceptionNamingSniff;
use SlevomatCodingStandard\Sniffs\Classes\SuperfluousInterfaceNamingSniff;
use SlevomatCodingStandard\Sniffs\Classes\SuperfluousTraitNamingSniff;
use SlevomatCodingStandard\Sniffs\Functions\FunctionLengthSniff;
use SlevomatCodingStandard\Sniffs\Functions\UnusedParameterSniff;
use SlevomatCodingStandard\Sniffs\Namespaces\UseSpacingSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\DisallowMixedTypeHintSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff;

return [
    'preset' => 'symfony',
    'ide' => 'phpstorm',
    'exclude' => [
        'vendor',
        'CLI/bats/php',
        'tests/Behat/UserContext/AuthenticatedUserContextTrait.php',
        // Multi-namespace function-override trick for openssl_encrypt test double
        'TwoFactorSecretEncryptorTest',
    ],
    'add' => [],
    'remove' => [
        UnusedParameterSniff::class,
        SuperfluousInterfaceNamingSniff::class,
        SuperfluousExceptionNamingSniff::class,
        SuperfluousTraitNamingSniff::class,
        SpaceAfterNotSniff::class,
        NunoMaduro\PhpInsights\Domain\Sniffs\ForbiddenSetterSniff::class,
        UseSpacingSniff::class,
        ForbiddenTraits::class,
    ],
    'config' => [
        ReturnTypeHintSniff::class => [
            'exclude' => [
                'src/User/Domain/Repository/UserRepositoryInterface',
                'tests/Unit/OAuth/Infrastructure/Manager/AccessTokenManagerTest.php',
                'tests/Unit/OAuth/Infrastructure/Revoker/CredentialsRevokerTest.php',
            ],
        ],
        ParameterTypeHintSniff::class => [
            'exclude' => [
                'tests/Unit/Shared/Infrastructure/Bus/CallableFirstParameterExtractorTest',
                'tests/Unit/Shared/Infrastructure/Bus/Stub/HandlerWithoutTypeHint',
                'tests/Behat/HealthCheckContext/HealthCheckContext.php',
            ],
        ],
        DisallowMixedTypeHintSniff::class => [
            'exclude' => [
                'tests/Unit/Shared/Infrastructure/Bus/Event/Async/RecordingLogger.php',
                'tests/Unit/Shared/Application/Collector/BatchEmailCollectorTest.php',
                'tests/Unit/Shared/Infrastructure/Observability/Resolver/ApiEndpointMetricDimensionsResolverTest.php',
                'tests/Unit/User/Domain/Factory/PasswordResetTokenFactoryTest.php',
                'tests/Integration/Auth/RouteAccessControlIntegrationTest.php',
            ],
        ],
        LineLengthSniff::class => [
            'exclude' => [
                'phpinsights',
                'tests/Behat/OAuthContext/OAuthContext.php',
                'src/User/Infrastructure/Repository/MariaDBPasswordResetTokenRepository.php',
                'tests/Integration/User/Infrastructure/Repository/CachePerformanceTest.php',
                'tests/Behat/UserContext/UserRequestContext.php',
                'tests/Behat/UserContext/UserResponseContext.php',
                'tests/Integration/Auth/DisablePasswordGrantIntegrationTest.php',
                'tests/Integration/User/Application/CommandHandler/SignInCommandHandlerIntegrationTest.php',
                'tests/Integration/User/Application/CommandHandler/UpdateUserCommandHandlerIntegrationTest.php',
                'tests/Unit/Shared/Auth/Factory/TestAccessTokenFactoryTest.php',
                'tests/Unit/User/Application/CommandHandler/CompleteTwoFactorCommandHandlerSuccessPathTest.php',
                'tests/Unit/User/Application/CommandHandler/CompleteTwoFactorCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/RefreshTokenCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/SetupTwoFactorCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/SignInCommandHandlerTest.php',
                'tests/Unit/User/Application/Processor/CompleteTwoFactorProcessorTest.php',
                'tests/Unit/User/Application/Processor/RegenerateRecoveryCodesProcessorTest.php',
                'tests/Unit/User/Application/Processor/SignInProcessorTest.php',
                'tests/Unit/User/Application/Service/PasswordChangeSessionRevokerTest.php',
                'tests/Unit/User/Application/Service/UserUpdateApplierTest.php',
                'tests/Unit/User/Infrastructure/Service/RedisAccountLockoutServiceTest.php',
                'tests/Unit/User/Infrastructure/Repository/CachedUserRepositoryFindByEmailTest.php',
                'tests/Unit/User/Infrastructure/Repository/CachedUserRepositoryFindByIdTest.php',
                'tests/Unit/User/Infrastructure/EventSubscriber/TwoFactorEventLogSubscriberTest.php',
                'tests/Integration/Auth/GraphQLAuthExclusionTest.php',
                'tests/Integration/Auth/JwtKeyPermissionsTest.php',
                'tests/Unit/User/Infrastructure/EventSubscriber/SecurityEventLogSubscriberTest.php',
                'tests/Unit/User/Infrastructure/EventSubscriber/SignInEventLogSubscriberTest.php',
                'tests/Integration/Auth/BcryptCostUpgradeTest.php',
                'tests/Integration/Auth/RouteAccessControlIntegrationTest.php',
                'tests/Integration/Auth/ApiRateLimitListenerIntegrationTest.php',
                'tests/Unit/Shared/Application/EventListener/ApiRateLimitListenerTest.php',
                'tests/Unit/User/Infrastructure/EventListener/SchemathesisCleanupListenerTestCase.php',
                'tests/Integration/Auth/GraphQLBatchRejectTest.php',
                'tests/Integration/Auth/ProductionConfigValidationTest.php',
                'tests/Unit/DataFixtures/Command/SeedSchemathesisDataCommandTest.php',
                'tests/Unit/DataFixtures/Seeder/SchemathesisUserSeederTest.php',
                'tests/Unit/OAuth/Infrastructure/Manager/AccessTokenManagerTest.php',
                'tests/Unit/OAuth/Infrastructure/Manager/ClientManagerTest.php',
                'tests/Unit/OAuth/Infrastructure/Revoker/CredentialsRevokerTest.php',
                'tests/Unit/Shared/Application/EventListener/InvalidUuidRequestListenerTest.php',
                'tests/Unit/Shared/Application/OpenApi/Builder/ArrayContextBuilderTest.php',
                'tests/Unit/Shared/Application/OpenApi/Builder/ArrayResponseBuilderTest.php',
                'tests/Unit/Shared/Application/OpenApi/Builder/ContextBuilderArrayTest.php',
                'tests/Unit/Shared/Application/OpenApi/Builder/ContextBuilderTest.php',
                'tests/Unit/Shared/Application/OpenApi/Builder/QueryParameterBuilderTest.php',
                'tests/Unit/Shared/Application/OpenApi/Builder/RequestBuilderTest.php',
                'tests/Unit/Shared/Application/OpenApi/Builder/ResponseBuilderTest.php',
                'tests/Unit/Shared/Application/OpenApi/Factory/Request/OAuthTokenRequestFactoryTest.php',
                'tests/Unit/Shared/Application/OpenApi/Factory/UriParameter/UuidUriParameterFactoryTest.php',
                'tests/Unit/Shared/Application/OpenApi/OpenApiFactoryTest.php',
                'tests/Unit/Shared/Application/OpenApi/Processor/ServerErrorResponseAugmenterTest.php',
                'tests/Unit/Shared/Application/QueryParameter/Pagination/ItemsPerPageRuleTest.php',
                'tests/Unit/Shared/Application/Validator/CreateUserBatchValidatorTest.php',
                'tests/Unit/Shared/Infrastructure/Bus/CallableFirstParameterExtractorTest.php',
                'tests/Unit/Shared/Infrastructure/Bus/Event/Async/MessengerAsyncEventDispatcherFailureTest.php',
                'tests/Unit/Shared/Infrastructure/Bus/Event/Async/ResilientAsyncEventDispatcherExecutionTest.php',
                'tests/Unit/Shared/Infrastructure/Bus/Event/Async/ResilientAsyncEventDispatcherLoggingTest.php',
                'tests/Unit/Shared/Infrastructure/Observability/Emitter/AwsEmfBusinessMetricsEmitterTest.php',
                'tests/Unit/Shared/Infrastructure/Observability/Formatter/EmfLogFormatterTest.php',
                'tests/Unit/Shared/Infrastructure/Security/DualAuthenticatorTest.php',
                'tests/Unit/User/Application/CommandHandler/ConfirmPasswordResetCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/DisableTwoFactorCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/RegisterUserBatchCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/RequestPasswordResetCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/SendConfirmationEmailCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/SignOutAllCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/SignOutCommandHandlerTest.php',
                'tests/Unit/User/Application/EventSubscriber/PasswordResetConfirmedEventSubscriberTest.php',
                'tests/Unit/User/Application/EventSubscriber/PasswordResetRequestedEventSubscriberTest.php',
                'tests/Unit/User/Application/EventSubscriber/UserRegisteredMetricsSubscriberTest.php',
                'tests/Unit/User/Application/EventSubscriber/UserUpdatedMetricsSubscriberTest.php',
                'tests/Unit/User/Application/Processor/ResendEmailProcessorTest.php',
                'tests/Unit/User/Application/Processor/SignOutAllProcessorTest.php',
                'tests/Unit/User/Application/Processor/SignOutProcessorTest.php',
                'tests/Unit/User/Application/Processor/UserPatchProcessorTestCase.php',
                'tests/Unit/User/Infrastructure/EventSubscriber/RefreshTokenEventLogSubscriberTest.php',
                'tests/Unit/User/Infrastructure/Factory/EmailFactoryTest.php',
            ],
            'ignoreComments' => true,
            'lineLimit' => 100,
        ],
        ForbiddenNormalClasses::class => [
            'exclude' => [
                'src/Shared/Infrastructure/Bus/Command/InMemorySymfonyCommandBus',
                'src/Shared/Infrastructure/Bus/Event/InMemorySymfonyEventBus',
                'src/Shared/OpenApi/Factory/Response/DuplicateEmailFactory',
                'src/User/Domain/Entity/User',
            ],
        ],
        UnnecessaryStringConcatSniff::class => [
            'exclude' => [
                'src/Shared/Application/OpenApi/Factory/Response/UnsupportedTypeFactory',
                'src/User/Domain/Exception/DuplicateEmailException',
                'src/Shared/Application/OpenApi/Factory/Response/DuplicateEmailFactory',
                'src/Shared/Infrastructure/Bus/Command/CommandNotRegisteredException',
                'src/Shared/Infrastructure/Bus/Event/EventNotRegisteredException.php',
                'tests/Unit/Shared/Application/OpenApi/Factory/Response/OAuthRedirectResponseFactoryTest',
                'tests/Unit/Shared/Application/OpenApi/Factory/Response/UnsupportedGrantTypeResponseFactoryTest',
                'tests/Behat/OAuthContext/OAuthContext',
            ],
        ],
        CyclomaticComplexityIsHigh::class => [
            'exclude' => [
                'src/Shared/Application/Validator/InitialsValidator.php',
                'src/Shared/Application/Validator/PasswordValidator.php',
                'tests/Unit/User/Infrastructure/Repository/CachedUserRepositoryTest.php',
                'tests/Integration/User/Infrastructure/Repository/CachePerformanceTest.php',
                'tests/Unit/User/Application/CommandHandler/CompleteTwoFactorCommandHandlerSuccessPathTest.php',
            ],
        ],
        FunctionLengthSniff::class => [
            'exclude' => [
                'tests/Unit/User/Infrastructure/Repository/CachedUserRepositoryTest.php',
                'tests/Unit/User/Application/EventSubscriber/ConfirmationEmailSendEventSubscriberTest.php',
                'tests/Unit/User/Application/EventSubscriber/EmailChangedEventSubscriberTest.php',
                'tests/Unit/User/Application/EventSubscriber/UserRegisteredEventSubscriberTest.php',
                'tests/Behat/UserContext/AuthenticatedUserContextTrait.php',
                'tests/Behat/UserContext/UserRequestContext.php',
                'tests/Behat/UserContext/UserResponseContext.php',
                'tests/Behat/UserGraphQLContext/UserGraphQLResponseContext.php',
                'tests/Integration/Auth/ApiRateLimitListenerIntegrationTest.php',
                'tests/Integration/Auth/DisablePasswordGrantIntegrationTest.php',
                'tests/Integration/Auth/RouteAccessControlIntegrationTest.php',
                'tests/Integration/User/Application/CommandHandler/SignInCommandHandlerIntegrationTest.php',
                'tests/Integration/User/Application/CommandHandler/UpdateUserCommandHandlerIntegrationTest.php',
                'tests/Unit/Shared/Application/EventListener/ApiRateLimitListenerTest.php',
                'tests/Unit/Shared/Application/EventListener/SecurityHeadersResponseListenerTest.php',
                'tests/Unit/Shared/Auth/Factory/TestAccessTokenFactoryTest.php',
                'tests/Unit/Shared/Infrastructure/Security/DualAuthenticatorTest.php',
                'tests/Unit/User/Application/Command/UpdateUserCommandTest.php',
                'tests/Unit/User/Application/CommandHandler/CompleteTwoFactorCommandHandlerSuccessPathTest.php',
                'tests/Unit/User/Application/CommandHandler/CompleteTwoFactorCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/ConfirmTwoFactorCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/DisableTwoFactorCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/RefreshTokenCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/RegenerateRecoveryCodesCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/SetupTwoFactorCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/SignInCommandHandlerTest.php',
                'tests/Unit/User/Application/CommandHandler/UpdateUserCommandHandlerTest.php',
                'tests/Unit/User/Application/EventSubscriber/SignInEventLogSubscriberTest.php',
                'tests/Unit/User/Application/Processor/CompleteTwoFactorProcessorTest.php',
                'tests/Unit/User/Application/Processor/ConfirmTwoFactorProcessorTest.php',
                'tests/Unit/User/Application/Processor/DisableTwoFactorProcessorTest.php',
                'tests/Unit/User/Application/Processor/RefreshTokenProcessorTest.php',
                'tests/Unit/User/Application/Processor/RegenerateRecoveryCodesProcessorTest.php',
                'tests/Unit/User/Application/Processor/ResendEmailProcessorTest.php',
                'tests/Unit/User/Application/Processor/SetupTwoFactorProcessorTest.php',
                'tests/Unit/User/Application/Processor/SignInProcessorTest.php',
                'tests/Unit/User/Application/Processor/UserPatchProcessorTestCase.php',
                'tests/Unit/User/Application/Processor/UserPutProcessorTest.php',
                'tests/Unit/User/Application/Resolver/UserUpdateMutationResolverTest.php',
                'tests/Unit/User/Application/Service/PasswordChangeSessionRevokerTest.php',
                'tests/Unit/User/Application/Service/UserUpdateApplierTest.php',
                'tests/Unit/User/Domain/Event/AllSessionsRevokedEventTest.php',
                'tests/Unit/User/Domain/Event/RefreshTokenTheftDetectedEventTest.php',
                'tests/Unit/User/Infrastructure/Repository/MongoDBRecoveryCodeRepositoryTest.php',
                'tests/Unit/User/Infrastructure/Service/LexikAccessTokenGeneratorTest.php',
                'tests/Unit/User/Infrastructure/Service/RedisAccountLockoutServiceTest.php',
                'tests/Unit/User/Application/CommandHandler/SignOutCommandHandlerTest.php',
                'tests/Unit/User/Application/Processor/SignOutProcessorTest.php',
                'tests/Unit/User/Application/CommandHandler/SignOutAllCommandHandlerTest.php',
                'tests/Unit/User/Infrastructure/EventSubscriber/SignInEventLogSubscriberTest.php',
                'tests/Integration/Auth/GraphQLBatchRejectTest.php',
                'tests/Unit/Shared/Application/EventListener/GraphQLBatchRejectListenerTest.php',
                'tests/Integration/Auth/GraphQLAuthExclusionTest.php',
                'tests/Integration/Auth/BcryptCostUpgradeTest.php',
                'tests/Integration/Auth/RouteAccessControlIntegrationTest.php',
            ],
        ],
        UselessOverridingMethodSniff::class => [
            'exclude' => [
                'tests/Unit/Shared/Infrastructure/Bus/Event/Async/TestDomainEvent.php',
                'tests/Unit/Shared/Infrastructure/Bus/Event/Async/TestEvent.php',
                'tests/Unit/Shared/Infrastructure/Bus/Event/Async/TestOtherDomainEvent.php',
                'tests/Unit/Shared/Infrastructure/Bus/Event/Async/ResilientAsyncEventBusTestEvent.php',
            ],
        ],
    ],
    'requirements' => [
        'min-quality' => 100,
        'min-complexity' => 95,
        'min-architecture' => 100,
        'min-style' => 100,
    ],
    'threads' => null,
];
