enum ButtonColorEnum {
  DEFAULT = '#FFFFFF',
  DEFAULT_ACTIVE = '#FFFFFF',
  DEFAULT_HOVER = '#FFFFFF',
  DEFAULT_DISABLED = '#FFFFFF',
  WHITE = '#1B2327',
  WHITE_ACTIVE = '#1B2327',
  WHITE_HOVER = '#1B2327',
  WHITE_DISABLED = '#FFFFFF',
}

export default ButtonColorEnum;
