openapi: 3.1.0
info:
  title: 'PHP Service Template API'
  description: 'This API provides endpoints to manage php service template data within a VilnaCRM.'
  version: 1.0.0
servers:
  -
    url: /
    description: ''
paths:
  /api/example_api_resources:
    get:
      operationId: api_example_api_resources_get
      tags:
        - ExampleApiResource
      responses:
        '200':
          description: 'ExampleApiResource resource'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleApiResource'
        '404':
          description: 'Resource not found'
      summary: 'Retrieves a ExampleApiResource resource.'
      description: 'Retrieves a ExampleApiResource resource.'
      parameters: []
      deprecated: false
  /api/health:
    get:
      operationId: api_health_get
      tags:
        - HealthCheck
      responses:
        '204':
          description: 'Health check passed with no content to return.'
        '500':
          description: 'Health check failed.'
      summary: 'Retrieves a HealthCheck resource.'
      description: 'Retrieves a HealthCheck resource.'
      parameters: []
      deprecated: false
components:
  schemas:
    ExampleApiResource:
      type: object
      description: ''
      deprecated: false
    HealthCheck:
      type: object
      description: ''
      deprecated: false
  responses: {  }
  parameters: {  }
  examples: {  }
  requestBodies: {  }
  headers: {  }
  securitySchemes: {  }
security: []
tags: []
webhooks: {  }
