extends: default

rules:
  document-start: disable

  indentation:
    spaces: 2
    level: warning

  line-length:
    max: 120
    level: warning

  new-line-at-end-of-file: enable

  new-lines:
    type: unix
