# .yaml-lint.yml

extends: default

rules:
  indentation:
    spaces: 2
    level: error

  max-line-length:
    max: 120
    level: warning

  new-line-at-end-of-file: enable

  document-end: enable

  line-ending:
    style: lf
