extends: default

rules:
  document-start: disable

  indentation:
    spaces: 2
    level: warning

  line-length:
    max: 120
    level: warning

  new-line-at-end-of-file:
    level: warning

  trailing-spaces:
    level: warning

  brackets:
    level: warning

  commas:
    level: warning

  braces:
    level: warning

  empty-lines:
    max: 0
    level: warning
