services:
  Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface:
    alias: 'security.token_storage'
    public: true

  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Behat\:
    resource: '../tests/Behat/*'
