resources:
  App\User\Domain\Entity\User:
    exceptionToStatus:
      'App\User\Domain\Exception\UserTimedOutException': 429
      'App\User\Infrastructure\Exception\UserNotFoundException': 404
      'App\User\Infrastructure\Exception\InvalidPasswordException': 410
      'App\User\Infrastructure\Exception\TokenNotFoundException': 404
      'App\User\Infrastructure\Exception\DuplicateEmailException': 409
    normalizationContext:
      groups: [ 'output' ]

    operations:
      ApiPlatform\Metadata\GetCollection:
        paginationClientItemsPerPage: true
      ApiPlatform\Metadata\Get: ~
      create_http:
        class: 'ApiPlatform\Metadata\Post'
        input: 'App\User\Application\DTO\UserRegisterDto'
        processor: 'App\User\Infrastructure\Processor\RegisterUserProcessor'
      confirm_http:
        class: 'ApiPlatform\Metadata\Patch'
        input: 'App\User\Application\DTO\ConfirmUserDto'
        processor: 'App\User\Infrastructure\Processor\ConfirmUserProcessor'
        uriTemplate: 'users/confirm'
      ApiPlatform\Metadata\Patch:
        input: 'App\User\Application\DTO\UserPatchDto'
        processor: 'App\User\Infrastructure\Processor\UserPatchProcessor'
      ApiPlatform\Metadata\Put:
        input: 'App\User\Application\DTO\UserPutDto'
        processor: 'App\User\Infrastructure\Processor\UserPutProcessor'
      ApiPlatform\Metadata\Delete: ~
      ApiPlatform\Metadata\Post:
        uriTemplate: '/users/{id}/resend-confirmation-email'
        input: 'App\User\Application\DTO\RetryDto'
        processor: 'App\User\Infrastructure\Processor\ResendEmailProcessor'

    graphQlOperations:
      - class: 'ApiPlatform\Metadata\GraphQl\Query'
      - class: 'ApiPlatform\Metadata\GraphQl\QueryCollection'
      - class: 'ApiPlatform\Metadata\GraphQl\DeleteMutation'
        normalizationContext:
          groups: [ 'deleteMutationOutput' ]
        name: 'delete'
      - class: 'ApiPlatform\Metadata\GraphQl\Mutation'
        name: 'confirm'
        resolver: 'App\User\Infrastructure\Resolver\ConfirmUserMutationResolver'
        deserialize: false
        denormalizationContext:
          groups: [ ]
        extraArgs:
          token:
            type: 'String!'
      - class: 'ApiPlatform\Metadata\GraphQl\Mutation'
        resolver: 'App\User\Infrastructure\Resolver\RegisterUserMutationResolver'
        deserialize: false
        name: 'create'
        denormalizationContext:
          groups: []
        extraArgs:
          email:
            type: 'String!'
          initials:
            type: 'String!'
          password:
            type: 'String!'
      - class: 'ApiPlatform\Metadata\GraphQl\Mutation'
        resolver: 'App\User\Infrastructure\Resolver\UserUpdateMutationResolver'
        deserialize: false
        write: false
        name: 'update'
        denormalizationContext:
          groups: []
        extraArgs:
          id:
            type: 'ID!'
          newPassword:
            type: 'String'
          password:
            type: 'String!'
          email:
            type: 'String'
          initials:
            type: 'String'
      - class: 'ApiPlatform\Metadata\GraphQl\Mutation'
        resolver: 'App\User\Infrastructure\Resolver\ResendEmailMutationResolver'
        name: 'resendEmailTo'
        denormalizationContext:
          groups: []
        extraArgs:
          id:
            type: 'ID!'
