#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
# shellcheck source=scripts/local-coder/lib/github-auth.sh
. "${ROOT_DIR}/scripts/local-coder/lib/github-auth.sh"
# shellcheck source=scripts/local-coder/lib/workspace-secrets.sh
. "${ROOT_DIR}/scripts/local-coder/lib/workspace-secrets.sh"

for SETTINGS_FILE in \
    "${ROOT_DIR}/.devcontainer/workspace-settings.env" \
    "${ROOT_DIR}/.devcontainer/codespaces-settings.env"; do
    if [ -f "${SETTINGS_FILE}" ]; then
        # shellcheck disable=SC1090
        . "${SETTINGS_FILE}"
        break
    fi
done

readonly AGENT_ENV_DIR="${HOME}/.config/user-service"
readonly AGENT_SECRETS_FILE="${AGENT_ENV_DIR}/agent-secrets.env"
readonly AGENT_BASHRC_FILE="${HOME}/.bashrc"
readonly AGENT_PROFILE_FILE="${HOME}/.profile"
readonly AGENT_BASHRC_START="# BEGIN USER-SERVICE AGENT ENV"
readonly AGENT_BASHRC_END="# END USER-SERVICE AGENT ENV"
readonly AGENT_PROFILE_START="# BEGIN USER-SERVICE AGENT ENV"
readonly AGENT_PROFILE_END="# END USER-SERVICE AGENT ENV"
readonly USER_NPM_GLOBAL_BIN="${HOME}/.npm-global/bin"

: "${CODEX_NPM_PACKAGE:=@openai/codex}"
: "${USER_SERVICE_BOOTSTRAP_STRICT:=${CODESPACES:-false}}"

: "${GH_HOST:=github.com}"
: "${GH_GIT_PROTOCOL:=ssh}"
: "${GH_PROMPT:=disabled}"
: "${WORKSPACE_GIT_IDENTITY_NAME:=vilnacrm ai bot}"
: "${WORKSPACE_GIT_IDENTITY_EMAIL:=info@vilnacrm.com}"
: "${WORKSPACE_GIT_COMMITTER_NAME:=}"
: "${WORKSPACE_GIT_COMMITTER_EMAIL:=}"
: "${CODESPACE_GIT_IDENTITY_NAME:=${WORKSPACE_GIT_IDENTITY_NAME}}"
: "${CODESPACE_GIT_IDENTITY_EMAIL:=${WORKSPACE_GIT_IDENTITY_EMAIL}}"
: "${CODESPACE_GIT_COMMITTER_NAME:=${WORKSPACE_GIT_COMMITTER_NAME}}"
: "${CODESPACE_GIT_COMMITTER_EMAIL:=${WORKSPACE_GIT_COMMITTER_EMAIL}}"

TMP_FILES=()
CS_GIT_IDENTITY_NAME=""
CS_GIT_IDENTITY_EMAIL=""
CS_GIT_COMMITTER_NAME=""
CS_GIT_COMMITTER_EMAIL=""
DETECTED_GIT_IDENTITY_NAME=""
DETECTED_GIT_IDENTITY_EMAIL=""
DETECTED_GIT_COMMITTER_NAME=""
DETECTED_GIT_COMMITTER_EMAIL=""

if [ -f "${AGENT_SECRETS_FILE}" ]; then
    # shellcheck disable=SC1090
    . "${AGENT_SECRETS_FILE}"
fi

if [ -f "${HOME}/.config/openclaw/agent-secrets.env" ]; then
    # shellcheck disable=SC1091
    . "${HOME}/.config/openclaw/agent-secrets.env"
fi

cs_load_host_workspace_secrets

cleanup_tmp_files() {
    local tmp_file
    for tmp_file in "${TMP_FILES[@]}"; do
        rm -f "${tmp_file}"
    done
}

track_tmp_file() {
    TMP_FILES+=("$1")
}

trap cleanup_tmp_files EXIT

persist_agent_secrets_file() {
    local tmp_secrets_file

    tmp_secrets_file="$(mktemp)"
    track_tmp_file "${tmp_secrets_file}"

    {
        printf '# Generated by workspace bootstrap\n'
        if [ -n "${OPENAI_API_KEY:-}" ]; then
            printf 'export OPENAI_API_KEY=%q\n' "${OPENAI_API_KEY}"
        fi
        if [ -n "${GH_AUTOMATION_TOKEN:-}" ]; then
            printf 'export GH_AUTOMATION_TOKEN=%q\n' "${GH_AUTOMATION_TOKEN}"
        fi
        if [ -n "${GH_TOKEN:-}" ]; then
            printf 'export GH_TOKEN=%q\n' "${GH_TOKEN}"
        elif [ -n "${GH_AUTOMATION_TOKEN:-}" ]; then
            printf 'export GH_TOKEN=%q\n' "${GH_AUTOMATION_TOKEN}"
        fi
        if [ -n "${GITHUB_TOKEN:-}" ]; then
            printf 'export GITHUB_TOKEN=%q\n' "${GITHUB_TOKEN}"
        elif [ -n "${GH_TOKEN:-}" ]; then
            printf 'export GITHUB_TOKEN=%q\n' "${GH_TOKEN}"
        elif [ -n "${GH_AUTOMATION_TOKEN:-}" ]; then
            printf 'export GITHUB_TOKEN=%q\n' "${GH_AUTOMATION_TOKEN}"
        fi
        printf 'export PATH=%q:$PATH\n' "${USER_NPM_GLOBAL_BIN}"
        if [ -n "${CS_GIT_IDENTITY_NAME:-}" ]; then
            printf 'export GIT_AUTHOR_NAME=%q\n' "${CS_GIT_IDENTITY_NAME}"
        fi
        if [ -n "${CS_GIT_IDENTITY_EMAIL:-}" ]; then
            printf 'export GIT_AUTHOR_EMAIL=%q\n' "${CS_GIT_IDENTITY_EMAIL}"
        fi
        if [ -n "${CS_GIT_COMMITTER_NAME:-}" ]; then
            printf 'export GIT_COMMITTER_NAME=%q\n' "${CS_GIT_COMMITTER_NAME}"
        elif [ -n "${CS_GIT_IDENTITY_NAME:-}" ]; then
            printf 'export GIT_COMMITTER_NAME=%q\n' "${CS_GIT_IDENTITY_NAME}"
        fi
        if [ -n "${CS_GIT_COMMITTER_EMAIL:-}" ]; then
            printf 'export GIT_COMMITTER_EMAIL=%q\n' "${CS_GIT_COMMITTER_EMAIL}"
        elif [ -n "${CS_GIT_IDENTITY_EMAIL:-}" ]; then
            printf 'export GIT_COMMITTER_EMAIL=%q\n' "${CS_GIT_IDENTITY_EMAIL}"
        fi
    } > "${tmp_secrets_file}"

    mkdir -p "${AGENT_ENV_DIR}"
    chmod 700 "${AGENT_ENV_DIR}"
    chmod 600 "${tmp_secrets_file}"
    mv "${tmp_secrets_file}" "${AGENT_SECRETS_FILE}"
}

upsert_agent_env_source_block() {
    local target_file="$1"
    local block_start="$2"
    local block_end="$3"
    local tmp_file

    tmp_file="$(mktemp)"
    track_tmp_file "${tmp_file}"

    touch "${target_file}"

    awk -v start="${block_start}" -v end="${block_end}" '
        $0 == start {skip=1; next}
        $0 == end {skip=0; next}
        skip == 0 {print}
    ' "${target_file}" > "${tmp_file}"

    cat >> "${tmp_file}" <<'EOM'

# BEGIN USER-SERVICE AGENT ENV
if [ -f "$HOME/.config/user-service/agent-secrets.env" ]; then
    . "$HOME/.config/user-service/agent-secrets.env"
fi
# END USER-SERVICE AGENT ENV
EOM

    cat "${tmp_file}" > "${target_file}"
    rm -f "${tmp_file}"
}

ensure_shell_sources_agent_secrets() {
    upsert_agent_env_source_block "${AGENT_BASHRC_FILE}" "${AGENT_BASHRC_START}" "${AGENT_BASHRC_END}"
    upsert_agent_env_source_block "${AGENT_PROFILE_FILE}" "${AGENT_PROFILE_START}" "${AGENT_PROFILE_END}"
}

configure_git_identity() {
    local author_name author_email committer_name committer_email configured_name configured_email var

    CS_GIT_IDENTITY_NAME=""
    CS_GIT_IDENTITY_EMAIL=""
    CS_GIT_COMMITTER_NAME=""
    CS_GIT_COMMITTER_EMAIL=""
    DETECTED_GIT_IDENTITY_NAME=""
    DETECTED_GIT_IDENTITY_EMAIL=""
    DETECTED_GIT_COMMITTER_NAME=""
    DETECTED_GIT_COMMITTER_EMAIL=""

    for var in GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL; do
        if [ -z "${!var:-}" ]; then
            unset "${var}" || true
        fi
    done

    author_name="${GIT_AUTHOR_NAME:-}"
    author_email="${GIT_AUTHOR_EMAIL:-}"
    committer_name="${GIT_COMMITTER_NAME:-}"
    committer_email="${GIT_COMMITTER_EMAIL:-}"
    configured_name="$(git config --global --get user.name 2>/dev/null || true)"
    configured_email="$(git config --global --get user.email 2>/dev/null || true)"

    if [ -z "${author_name}" ]; then
        author_name="${configured_name}"
    fi
    if [ -z "${author_email}" ]; then
        author_email="${configured_email}"
    fi
    if [ -z "${committer_name}" ]; then
        committer_name="${configured_name}"
    fi
    if [ -z "${committer_email}" ]; then
        committer_email="${configured_email}"
    fi

    if [ -z "${author_name}" ]; then
        author_name="${WORKSPACE_GIT_IDENTITY_NAME}"
    fi
    if [ -z "${author_email}" ]; then
        author_email="${WORKSPACE_GIT_IDENTITY_EMAIL}"
    fi
    if [ -z "${committer_name}" ]; then
        committer_name="${WORKSPACE_GIT_COMMITTER_NAME:-${author_name}}"
    fi
    if [ -z "${committer_email}" ]; then
        committer_email="${WORKSPACE_GIT_COMMITTER_EMAIL:-${author_email}}"
    fi

    git config --global user.name "${author_name}"
    git config --global user.email "${author_email}"

    export GIT_AUTHOR_NAME="${author_name}"
    export GIT_AUTHOR_EMAIL="${author_email}"
    export GIT_COMMITTER_NAME="${committer_name}"
    export GIT_COMMITTER_EMAIL="${committer_email}"

    CS_GIT_IDENTITY_NAME="${author_name}"
    CS_GIT_IDENTITY_EMAIL="${author_email}"
    CS_GIT_COMMITTER_NAME="${committer_name}"
    CS_GIT_COMMITTER_EMAIL="${committer_email}"
    DETECTED_GIT_IDENTITY_NAME="${author_name}"
    DETECTED_GIT_IDENTITY_EMAIL="${author_email}"
    DETECTED_GIT_COMMITTER_NAME="${committer_name}"
    DETECTED_GIT_COMMITTER_EMAIL="${committer_email}"
}

ensure_codex_cli() {
    export PATH="${USER_NPM_GLOBAL_BIN}:${PATH}"

    if command -v codex >/dev/null 2>&1; then
        return 0
    fi

    cs_require_command npm

    mkdir -p "${HOME}/.npm-global"
    npm config set prefix "${HOME}/.npm-global" >/dev/null 2>&1 || true
    npm install -g "${CODEX_NPM_PACKAGE}"

    if ! command -v codex >/dev/null 2>&1; then
        cat >&2 <<'EOM'
Error: Codex CLI installation completed but 'codex' is still not in PATH.
Ensure npm global bin is available in the current shell.
EOM
        return 1
    fi
}

cs_require_command gh
if ! cs_ensure_gh_auth; then
    if [ "${USER_SERVICE_BOOTSTRAP_STRICT}" = "1" ] || [ "${USER_SERVICE_BOOTSTRAP_STRICT}" = "true" ]; then
        exit 1
    fi
    export CS_GH_AUTH_MODE="unavailable"
    echo "Warning: GitHub authentication is not available; continuing with workspace-local defaults." >&2
fi

codex_ready=false
if command -v codex >/dev/null 2>&1; then
    codex_ready=true
else
    ensure_codex_cli
    codex_ready=true
fi

codex_login_ready=false
if [ "${codex_ready}" = true ] && codex login status >/dev/null 2>&1; then
    codex_login_ready=true
    unset OPENAI_API_KEY
fi

if [ "${codex_ready}" = true ] && [ "${codex_login_ready}" != true ] && [ -z "${OPENAI_API_KEY:-}" ]; then
    if [ "${USER_SERVICE_BOOTSTRAP_STRICT}" = "1" ] || [ "${USER_SERVICE_BOOTSTRAP_STRICT}" = "true" ]; then
        cat >&2 <<'EOM'
Error: Codex authentication is not configured.
Provide OPENAI_API_KEY in your workspace secrets or run:
  codex login
EOM
        exit 1
    fi
    echo "Warning: Codex authentication is not configured; continuing without AI bootstrap." >&2
fi

configure_git_identity
persist_agent_secrets_file
ensure_shell_sources_agent_secrets

gh config set git_protocol "${GH_GIT_PROTOCOL}" --host "${GH_HOST}" >/dev/null 2>&1 || true
gh config set prompt "${GH_PROMPT}" >/dev/null 2>&1 || true

codex_version=""
if [ "${codex_ready}" = true ]; then
    codex_version="$(codex --version 2>/dev/null || true)"
fi

echo "Secure agent environment is ready."
echo "GH auth: ${CS_GH_AUTH_MODE:-unavailable}."
echo "Git identity configured:"
echo "  - author name: ${DETECTED_GIT_IDENTITY_NAME:-<unset>}"
echo "  - author email: ${DETECTED_GIT_IDENTITY_EMAIL:-<unset>}"
echo "  - committer name: ${DETECTED_GIT_COMMITTER_NAME:-<unset>}"
echo "  - committer email: ${DETECTED_GIT_COMMITTER_EMAIL:-<unset>}"
if [ "${codex_ready}" = true ]; then
    echo "Codex configured:"
    echo "  - command: $(command -v codex)"
    echo "  - version: ${codex_version:-unknown}"
    echo "  - npm package: ${CODEX_NPM_PACKAGE}"
else
    echo "Codex configured: unavailable."
fi
