name: CLI testing

on:
  pull_request:
    branches: ['main']

jobs:
  bats_core_tests:
    runs-on: ubuntu-latest
    name: Run Bats Core Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Start Application
        run: make start

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@e424f8b8f722bf06a64acb1e10d8c437cd4170e6 # 2.0.0
        with:
          support-path: ${{ github.workspace }}/tests/CLI/bats/bats-support
          assert-path: ${{ github.workspace }}/tests/CLI/bats/bats-assert

      - name: Run Bats tests
        run: make bats
