name: CLI testing

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  bats_core_tests:
    runs-on: ubuntu-latest
    name: Run Bats Core Tests
    steps:
      - name: Dependabot skip
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
        run: echo "Skipping Bats for Dependabot PR"

      - name: Checkout Repository
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Docker
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        uses: docker/setup-docker-action@v4

      - uses: shivammathur/setup-php@v2
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Install Dependencies
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Start Application
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: make start

      - name: Install Bats and bats libs
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends \
            bats=1.10.0-1 \
            bats-support=0.3.0-4 \
            bats-assert=2.1.0-3

      - name: Install Bats plugins
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: |
          ln -s /usr/lib/bats/bats-support tests/CLI/bats/bats-support
          ln -s /usr/lib/bats/bats-assert tests/CLI/bats/bats-assert

      - name: Run Bats tests
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: make bats
