name: Codecov Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: echo "Skipping Codecov report for Dependabot PR"

      - name: Checkout Repository
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Start application
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: make start

      - name: Setup test database
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: make setup-test-db

      - name: Run unit tests and collect coverage
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: make coverage-xml

      - name: Copy coverage.xml to workspace
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: cp coverage/coverage.xml /tmp/coverage.xml

      - name: Check if coverage.xml exists
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: |
          if [ ! -f /tmp/coverage.xml ]; then
            echo "coverage.xml does not exist and cannot be uploaded."
            exit 1
          fi

      - name: Upload coverage to Codecov
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: /tmp/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
