name: Static analysis and fixers

on:
  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token with necessary permissions
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.VILNACRM_APP_ID }}
          private_key: ${{ secrets.VILNACRM_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - name: Run Super-Linter
        continue-on-error: true
        uses: super-linter/super-linter@v7.1.0
        env:
          FILTER_REGEX_EXCLUDE: '^\.github/openapi-spec/'
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          VALIDATE_YAML: true
          FIX_YAML_PRETTIER: true
          VALIDATE_YAML_PRETTIER: true
          VALIDATE_ENV: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          FIX_JAVASCRIPT_PRETTIER: true
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Commit and push linting fixes
        if: >
          github.event_name == 'pull_request' && github.ref_name !=
          github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref ||
            github.ref }}
          commit_message: 'chore(#${{ toJSON(github.event.number) }}): fix linting issues'
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
          token: ${{ steps.generate_token.outputs.token }}
