name: Codecov Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')
        run: echo "Skipping Codecov report for Dependabot PR"

      - name: Checkout Repository
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        uses: actions/checkout@v4

      - name: Start application
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: make start

      - name: Setup test database
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: make setup-test-db

      - name: Run unit tests and collect coverage
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: make coverage-xml

      - name: Copy coverage.xml to workspace
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: cp coverage/coverage.xml /tmp/coverage.xml

      - name: Check if coverage.xml exists
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: |
          if [ ! -f /tmp/coverage.xml ]; then
            echo "coverage.xml does not exist and cannot be uploaded."
            exit 1
          fi

      - name: Upload coverage to Codecov
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: /tmp/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
