name: Deploy to production

on:
  push:
    branches: ['main']

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build, tag, and push Docker image
        run: |
          IMAGE_URI="${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}"

          echo "Building Docker image..."
          docker build --target app_php -t "${IMAGE_URI}:latest" -f Dockerfile .

          echo "Pushing Docker image to ECR..."
          docker push "${IMAGE_URI}:latest"
