name: Architecture static analysis tool

on:
  pull_request:
    branches: ['main']

jobs:
  deptrac:
    name: Deptrac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Application
        run: make start

      - name: Run Deptrac
        run: make deptrac
