name: e2e testing

on:
  pull_request:
    branches: ['main']

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: pnpm run start
          wait-on: 'http://localhost:3000'
          browser: chrome
