name: E2E testing

on:
  pull_request:
    branches: ['main']

jobs:
  behat:
    name: Behat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Application
        run: make start

      - name: Run Behat Tests
        run: make behat
