name: E2E testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  behat:
    name: Behat
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          while ! docker system info > /dev/null 2>&1; do sleep 1; done

      - name: Start application
        run: make start

      - name: Setup test db
        run: make setup-test-db

      - name: Run Behat tests
        run: make e2e-tests
