name: E2E testing

on:
  pull_request:
    branches: ['main']

jobs:
  behat:
    name: Behat
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')
        run: echo "Skipping Behat tests for Dependabot PR"

      - name: Checkout Repository
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Install Dependencies
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Start Application
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: make start

      - name: Setup Test Database
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: make setup-test-db

      - name: Run Behat Tests
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: make e2e-tests
