name: E2E testing

on:
  pull_request:
    branches: ['main']

jobs:
  behat:
    name: Behat
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: contains(toLower(github.actor), 'dependabot')
        run: echo "Skipping Behat tests for Dependabot PR"

      - name: Checkout Repository
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Install Dependencies
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Start Application
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        run: make start

      - name: Setup Test Database
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        run: make setup-test-db

      - name: Run Behat Tests
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        run: make e2e-tests
