name: GraphQL spec backward comparability

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write

jobs:
  graphql-diff:
    name: Openapi-diff
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')
        run: echo "Skipping GraphQL diff checks for Dependabot PR"

      - name: Generate token with necessary permissions
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.VILNACRM_APP_ID }}
          private_key: ${{ secrets.VILNACRM_APP_PRIVATE_KEY }}

      - uses: shivammathur/setup-php@v2
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Checkout Repository
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        uses: actions/checkout@v4.2.1
        with:
          token: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) && steps.generate_token.outputs.token || github.token }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install Dependencies
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Start application
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: make start

      - name: Generate GraphQL spec
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: make generate-graphql-spec

      - name: Copy openapi spec to host
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        run: docker cp user-service-php-1:/srv/app/.github/graphql-spec/spec .github/graphql-spec/spec

      - name: Commit changes
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/graphql-spec/spec'
          message: 'feat(#${{ github.event.number }}): generate graphql spec'

      - name: GraphQL Inspector
        if: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) }}
        uses: kamilkisiela/graphql-inspector@release-1701263349990
        with:
          schema: 'master:.github/graphql-spec/spec'
        env:
          GITHUB_TOKEN: ${{ !(contains(github.actor, 'dependabot') || contains(github.head_ref, 'dependabot/') || contains(github.ref_name, 'dependabot/')) && steps.generate_token.outputs.token || github.token }}
