name: Mutation testing

on:
  pull_request:
    branches: ['main']

jobs:
  infection:
    name: Infection
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: github.actor == 'dependabot[bot]'
        run: echo "Skipping Infection for Dependabot PR"

      - name: Checkout code
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Install Dependencies
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run infection
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: CI=1 make infection
