name: Mutation testing

on:
  pull_request:
    branches: ['main']

jobs:
  infection:
    name: Infection
    runs-on: ubuntu-latest
    env:
      COMPOSE_PROJECT_NAME: user-service-infection
      COMPOSE_FILE: docker-compose.yml:docker-compose.memory-tests.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start application
        run: make start

      - name: Run infection
        run: make infection
