name: Mutation testing

on:
  pull_request:
    branches: ['main']

jobs:
  infection:
    name: Infection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Start application
        run: make start

      - name: Run infection
        run: make infection
