name: integration testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start application
        run: make start

      - name: Install Dependencies
        run: make install

      - name: Run migrations
        run: make doctrine-migrations-migrate

      - name: Execute Integration tests via PHPUnit
        run: make phpunit-integration
