name: Load testing

on:
  pull_request:
    branches: ['main']

jobs:
  load-tests:
    name: K6
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: echo "Skipping load tests for Dependabot PR"

      - name: Checkout Repository
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        uses: actions/checkout@v4

      - name: Setup Docker
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        uses: docker/setup-docker-action@v4

      - name: Start application
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: make start

      - name: Setup test db
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: make setup-test-db

      - name: Run load tests
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        env:
          API_HOST: localhost
          API_PORT: 8081
        run: make smoke-load-tests
