name: Memory leak testing

on:
  pull_request:
    branches: ['main']

concurrency:
  group: memory-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  memory-tests:
    name: Memory leak tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start application
        run: make start-memory-tests

      - name: Execute memory leak tests
        run: make memory-tests
