name: Validate OpenAPI Spec

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  validate-openapi:
    name: Spectral Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Start Application
        run: make start

      - name: Validate OpenAPI spec
        run: make validate-openapi-spec
