name: OpenApi spec backward comparability

on:
  pull_request:
    branches: [ "main" ]

jobs:
  openapi-diff:
    name: Openapi-diff
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start application
        run: make start

      - name: Setup test db
        run: make setup-test-db

      - name: Fix permissions
        run: make fix-perms

      - name: Generate openapi spec
        run: php bin/console --env=test api:openapi:export --yaml --output=.github/openapi-spec/spec.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/openapi-spec/spec.yaml'
          message: 'feat(#${{ toJSON(github.event.number) }}): generate openapi spec'

      - name: Check out head branch
        uses: actions/checkout@v3
        with:
          path: head

      - name: Check out master branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: base

      - name: Run OpenAPI Diff
        uses: docker://openapitools/openapi-diff:latest
        with:
          args: --fail-on-incompatible base/.github/openapi-spec/spec.yaml head/.github/openapi-spec/spec.yaml
