name: OpenApi spec backward compatibility

on:
  pull_request:
    branches: ['main']

jobs:
  openapi-diff:
    name: Openapi-diff
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Start application
        run: make start

      - name: Setup test db
        run: make setup-test-db

      - name: Generate openapi spec
        run: make generate-openapi-spec

      - name: Copy openapi spec to host
        run: docker cp user-service-php-1:/srv/app/.github/openapi-spec/spec.yaml .github/openapi-spec/spec.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/openapi-spec/spec.yaml'
          message: 'feat(#${{ toJSON(github.event.number) }}): generate openapi spec'

      - name: Check out head branch
        uses: actions/checkout@v3
        with:
          path: head

      - name: Check out master branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: base

      - name: Run OpenAPI Diff
        uses: docker://openapitools/openapi-diff:latest
        with:
          args: --fail-on-incompatible base/.github/openapi-spec/spec.yaml head/.github/openapi-spec/spec.yaml
