name: code quality

on:
  pull_request:
    branches: ['main']

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    name: PHP Insights checks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Application
        run: make start

      - name: Run PHPInsights
        run: make phpinsights
