name: code quality

on:
  pull_request:
    branches: ['main']

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Start application
        run: make start

      - name: Psalm
        run: make psalm

      - name: Psalm Security
        run: |
          rm -f results.sarif
          make psalm-security-sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3.25.4
        with:
          sarif_file: results.sarif
