name: code quality

on:
  pull_request:
    branches: ['main']

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: github.actor == 'dependabot[bot]'
        run: echo "Skipping Psalm for Dependabot PR"

      - name: Checkout code
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@v4

      - name: Setup PHP
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}
          tools: composer
          coverage: none
          ini-values: memory_limit=-1

      - name: Install dependencies
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs

      - name: Psalm
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: vendor/bin/psalm --output-format=github --no-diff

      - name: Psalm Security
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: vendor/bin/psalm --taint-analysis --output-format=sarif --report=results.sarif --no-diff

      - name: Upload Security Analysis results to GitHub
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
