name: Rector Code Refactoring

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  rector:
    runs-on: ubuntu-latest
    env:
      RECTOR_MODE: ci
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Application
        run: make start

      - name: Run Rector (Dry Run with Exit on Diff)
        run: make rector-ci
