name: Rector Code Refactoring

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  rector:
    runs-on: ubuntu-latest
    env:
      RECTOR_MODE: ci
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Install Dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run Rector (Dry Run with Exit on Diff)
        run: CI=1 make rector-ci
