name: Fuzz testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  restler:
    name: Restler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone RESTler Repository
        run: git clone https://github.com/microsoft/restler-fuzzer.git

      - name: Copy files
        run: |
          cp ./infrastructure/restler/Dockerfile ./restler-fuzzer/Dockerfile
          cp ./.github/openapi-spec/spec.yaml ./restler-fuzzer/

      - name: Run RESTler Build Script
        run: |
          cd restler-fuzzer
          docker build -t restler .

      - name: Start application
        run: make start

      - name: Install Dependencies
        run: make install

      - name: Run migrations
        run: make doctrine-migrations-migrate

        # Last mode takes too much time, so it will be executed in CD pipeline
      - name: Run Fuzz testing
        run: |
          docker run --network=host restler sh -c "/RESTler/restler/Restler compile --api_spec spec.yaml \
            && /RESTler/restler/Restler test --grammar_file ./Compile/grammar.py --dictionary_file ./Compile/dict.json --settings ./Compile/engine_settings.json --no_ssl \
            && /RESTler/restler/Restler fuzz-lean --grammar_file ./Compile/grammar.py --dictionary_file ./Compile/dict.json --settings ./Compile/engine_settings.json --no_ssl"