name: checks

on:
  pull_request:
    branches: ['main']

jobs:
  symfony-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start Application
        run: make start
      - name: Composer validate
        run: make composer-validate
      - name: Check symfony requirements
        run: make check-requirements
      - name: Symfony security check
        run: make check-security
