name: checks

on:
  pull_request:
    branches: ['main']

jobs:
  symfony-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: github.actor == 'dependabot[bot]'
        run: echo "Skipping symfony checks for Dependabot PR"

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        if: ${{ github.actor != 'dependabot[bot]' }}

      - name: Copy .env.test.local
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: Cache Composer packages
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: composer-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Symfony CLI
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: wget https://get.symfony.com/cli/installer -O - | bash

      - name: Composer validate
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: composer validate

      - name: Check symfony requirements
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: /home/runner/.symfony5/bin/symfony check:requirements

      - name: Symfony security check
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: /home/runner/.symfony5/bin/symfony security:check
