name: Template Sync

on:
  schedule:
    - cron: '0 9 * * MON'
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token to read from source repo
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ secrets.VILNACRM_APP_ID }}
          private_key: ${{ secrets.VILNACRM_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@8a0f668b83c32a0f673353086d74f12b8853d4f5
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          source_repo_path: VilnaCRM-Org/php-service-template
          upstream_branch: main
          pr_labels: template_sync
          is_force_push_pr: true
