name: testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Start application
        run: make start

      - name: Install Dependencies
        run: make install

      - name: Run migrations
        run: make doctrine-migrations-migrate

      - name: Fix permissions
        run: make fix-perms

      - name: Execute Unit and Integration tests
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
