name: Unit and Integration testing

on:
  pull_request:
    branches: ['main']

jobs:
  tests:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start application
        run: make start

      - name: Setup test db
        run: make setup-test-db

      - name: Execute Unit and Integration tests
        run: make ci-tests

      - name: Copy coverage report to host
        run: docker cp user-service-php-1:/coverage/coverage.xml /tmp

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /tmp/coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
