name: testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start application
        run: make start

      - name: Install Dependencies
        run: make install

      - name: Setup test db
        run: make ci-setup-test-db

      - name: Execute Unit tests
        run: make ci-unit-tests

      - name: Execute Integration tests
        run: make ci-integration-tests

      - name: Copy coverage report to host
        run: docker cp php:/coverage/coverage.xml coverage/

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/unitCoverage.xml,coverage/integrationCoverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
