name: Unit and Integration testing

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  tests:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: echo "Skipping PHPUnit for Dependabot PR"

      - name: Checkout Repository
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Start application
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: make start

      - name: Setup test db
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: make setup-test-db

      - name: Assert passkey readiness
        run: make passkey-test-readiness

      - name: Assert production-mode passkey readiness
        run: make passkey-ci-production-readiness

      - name: Execute Unit and Integration tests
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: make tests-with-coverage

      - name: Copy coverage report to host
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: docker cp user-service-php-1:/coverage/coverage.xml /tmp

      - name: Upload code coverage to Codecov
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /tmp/coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
