name: Visual Tests

on:
  pull_request:
    branches:
      - main

jobs:
  visual-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run visual tests
        run: pnpm run dev & pnpm exec playwright test ./src/test/visual

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: visual-test-report
          path: playwright-report/
          retention-days: 30
