name: Visual Tests

on:
  pull_request:
    branches:
      - main

env:
  PW_TEST_HTML_REPORT_OPEN: "never"

jobs:
  visual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Start application
        run: make start

      - name: Run visual tests
        run: make test-visual

